function buildBridgeDispatchDeps(context = {}, deps = {}) {
    const opsContext = context.opsContext || null;
    const {
        opsLogger,
        handleDirectBridgeCommand,
        engine,
        anki,
        config,
        parseStructuredCommand,
        appendExternalLinks,
        withApiMeta,
        buildCodexDegradedMeta,
        buildDuelModeMeta,
        buildProjectRoutePayload,
        parseTransportEnvelopeContext,
        runOpsCommand,
        handlePersonalRoute,
        processWordTokens,
        normalizeNewsCommandPayload,
        pickPreferredModelMeta,
        handlePromptPayload,
        loadNewsDigest,
        handleAutoBridgeCommand,
        normalizeIncomingCommandText,
        normalizeRequester,
        handleCodexBotAutoCommand,
        parseReportModeCommand,
        writeReportMode,
        routeByPrefix,
        captureConversationSafe,
        isResultFollowupQuery,
        resolveRecentResult,
        rememberActionableResult,
        followupStatePath,
        followupTtlMs,
        followupMaxEntriesPerSession,
        followupMaxSessions,
        followupResultKeywords,
        isAutoRouteAllowed,
        buildAllowlistBlockedResponse,
        enqueueHubDelegationCommand,
        handleAutoRoutedCommand,
        normalizeReportNewsPayload,
        isResearchRuntime,
        buildLinkOnlyReply,
        buildQuickStatusReply,
        inferPathListReply,
        buildGogNoPrefixGuide,
        buildNoPrefixReply,
        isHubRuntime,
        buildDailyCasualNoPrefixReply,
        buildNoPrefixGuide,
        loadMemoJournal,
        loadBlogPublisher,
        loadWeeklyReport,
        loadDailySummary,
    } = deps;

    return {
        handleDirectBridgeCommand,
        directCommandDeps: {
            engine,
            anki,
            config,
            parseStructuredCommand,
            appendExternalLinks,
            withApiMeta,
            buildCodexDegradedMeta,
            buildDuelModeMeta,
            buildProjectRoutePayload,
            parseTransportEnvelopeContext,
            runOpsCommand,
            handlePersonalRoute,
            processWordTokens,
            normalizeNewsCommandPayload,
            pickPreferredModelMeta,
            handlePromptPayload,
            loadNewsDigest,
        },
        handleAutoBridgeCommand,
        normalizeIncomingCommandText,
        parseTransportEnvelopeContext,
        normalizeRequester,
        handleCodexBotAutoCommand,
        withApiMeta,
        parseReportModeCommand,
        writeReportMode,
        routeByPrefix,
        logAutoRoute: ({ routed }) => {
            opsLogger.logStep(opsContext, {
                component: 'router',
                action: 'auto_route',
                message: `Auto route resolved to ${routed.route || 'none'}.`,
            });
        },
        captureConversationSafe,
        isResultFollowupQuery,
        resolveRecentResult,
        rememberActionableResult,
        followupStatePath,
        followupTtlMs,
        followupMaxEntriesPerSession,
        followupMaxSessions,
        followupResultKeywords,
        isAutoRouteAllowed,
        buildAllowlistBlockedResponse,
        enqueueHubDelegationCommand,
        handleAutoRoutedCommand,
        appendExternalLinks,
        pickPreferredModelMeta,
        normalizeNewsCommandPayload,
        normalizeReportNewsPayload,
        isResearchRuntime,
        parseStructuredCommand,
        buildCodexDegradedMeta,
        buildDuelModeMeta,
        buildProjectRoutePayload,
        handlePromptPayload,
        buildLinkOnlyReply,
        buildQuickStatusReply,
        runOpsCommand,
        inferPathListReply,
        buildGogNoPrefixGuide,
        buildNoPrefixReply,
        isHubRuntime,
        buildDailyCasualNoPrefixReply,
        buildNoPrefixGuide,
        handlePersonalRoute,
        processWordTokens,
        loadMemoJournal,
        loadNewsDigest,
        loadBlogPublisher,
        loadWeeklyReport,
        loadDailySummary,
    };
}

module.exports = {
    buildBridgeDispatchDeps,
};
