const assert = require('assert');

const publish = require('./blog_publish_from_reports');
let migrate;
try {
  migrate = require('./migrate_blog_taxonomy');
} catch (e) {
  migrate = {};
}

function run() {
  assert.strictEqual(typeof publish.getDefaultLangsForMode, 'function', 'getDefaultLangsForMode must be exported');
  assert.deepStrictEqual(publish.getDefaultLangsForMode('log'), ['en']);
  assert.deepStrictEqual(publish.getDefaultLangsForMode('briefing'), ['en', 'ja', 'ko']);
  assert.deepStrictEqual(publish.getDefaultLangsForMode('project'), ['en', 'ja', 'ko']);

  assert.strictEqual(typeof publish.shouldSyncToNotion, 'function', 'shouldSyncToNotion must be exported');
  assert.strictEqual(publish.shouldSyncToNotion({ category: 'project', lang: 'en' }), true);
  assert.strictEqual(publish.shouldSyncToNotion({ category: 'project', lang: 'ja' }), false);
  assert.strictEqual(publish.shouldSyncToNotion({ category: 'log', lang: 'en' }), false);

  assert.strictEqual(typeof migrate.classifyCategory, 'function', 'classifyCategory must be exported');
  assert.strictEqual(migrate.classifyCategory('Anki OpenClaw 연동 포트폴리오', 'project architecture and outcomes', ['portfolio']), 'project');
  assert.strictEqual(migrate.classifyCategory('작업 비망록 2026-02-07', 'daily briefing and summary', ['memoir']), 'briefing');
  assert.strictEqual(migrate.classifyCategory('Work Log 2026-02-07', 'misc operations log', ['ops-log']), 'log');
  assert.strictEqual(
    migrate.classifyCategory('AI 운영 로그 2026-02-07', 'summary generated by bot', ['ops-log']),
    'log',
  );
  assert.strictEqual(
    migrate.classifyCategory('Daily Briefing 2026-02-07', 'work log snippets included', ['daily']),
    'briefing',
  );

  console.log('test_blog_taxonomy_policy: ok');
}

run();
